### PR TITLE
add edge reader by ngql

### PR DESCRIPTION
**Pull request by MeeCreeps**
Read subgraph edge data via ngql as input to the nebula-algorithm side

### CODE REVIEW

**Comment by Nicole00** [comment]
Thanks for your idea and pr.
Connector uses java storage client and uses Scan interface to read NebulaGraph's data. The Scan interface has one param named filter, which would resolve your requirement. But sadly this filter param is not implemented yet.
And I thank your pr maybe a business solution, can you push it to branch `community_ngql`?

**Comment by MeeCreeps** [comment]
ok,thanks for your reply, I will push it to bash comunity_ngql 
and could you please tell me about the filter ?

**Comment by Nicole00** [comment]
could you please resolve the conflict?

**Comment by MeeCreeps** [comment]
hi,I  resolve the conflict , could you review it

**Review by caton-hpg — APPROVED** [review]

**Pull request merged**
